/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.goldolphin.silvan.avro;  
@SuppressWarnings("all")
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"net.goldolphin.silvan.avro\",\"fields\":[{\"name\":\"primaryName\",\"type\":\"string\"},{\"name\":\"secondaryName\",\"type\":\"string\"},{\"name\":\"subline\",\"type\":\"string\"},{\"name\":\"spec\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"string\"},{\"name\":\"url\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence primaryName;
  @Deprecated public java.lang.CharSequence secondaryName;
  @Deprecated public java.lang.CharSequence subline;
  @Deprecated public java.lang.CharSequence spec;
  @Deprecated public java.lang.CharSequence price;
  @Deprecated public java.lang.CharSequence url;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return primaryName;
    case 1: return secondaryName;
    case 2: return subline;
    case 3: return spec;
    case 4: return price;
    case 5: return url;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: primaryName = (java.lang.CharSequence)value$; break;
    case 1: secondaryName = (java.lang.CharSequence)value$; break;
    case 2: subline = (java.lang.CharSequence)value$; break;
    case 3: spec = (java.lang.CharSequence)value$; break;
    case 4: price = (java.lang.CharSequence)value$; break;
    case 5: url = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'primaryName' field.
   */
  public java.lang.CharSequence getPrimaryName() {
    return primaryName;
  }

  /**
   * Sets the value of the 'primaryName' field.
   * @param value the value to set.
   */
  public void setPrimaryName(java.lang.CharSequence value) {
    this.primaryName = value;
  }

  /**
   * Gets the value of the 'secondaryName' field.
   */
  public java.lang.CharSequence getSecondaryName() {
    return secondaryName;
  }

  /**
   * Sets the value of the 'secondaryName' field.
   * @param value the value to set.
   */
  public void setSecondaryName(java.lang.CharSequence value) {
    this.secondaryName = value;
  }

  /**
   * Gets the value of the 'subline' field.
   */
  public java.lang.CharSequence getSubline() {
    return subline;
  }

  /**
   * Sets the value of the 'subline' field.
   * @param value the value to set.
   */
  public void setSubline(java.lang.CharSequence value) {
    this.subline = value;
  }

  /**
   * Gets the value of the 'spec' field.
   */
  public java.lang.CharSequence getSpec() {
    return spec;
  }

  /**
   * Sets the value of the 'spec' field.
   * @param value the value to set.
   */
  public void setSpec(java.lang.CharSequence value) {
    this.spec = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.CharSequence getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.CharSequence value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /** Creates a new Product RecordBuilder */
  public static net.goldolphin.silvan.avro.Product.Builder newBuilder() {
    return new net.goldolphin.silvan.avro.Product.Builder();
  }
  
  /** Creates a new Product RecordBuilder by copying an existing Builder */
  public static net.goldolphin.silvan.avro.Product.Builder newBuilder(net.goldolphin.silvan.avro.Product.Builder other) {
    return new net.goldolphin.silvan.avro.Product.Builder(other);
  }
  
  /** Creates a new Product RecordBuilder by copying an existing Product instance */
  public static net.goldolphin.silvan.avro.Product.Builder newBuilder(net.goldolphin.silvan.avro.Product other) {
    return new net.goldolphin.silvan.avro.Product.Builder(other);
  }
  
  /**
   * RecordBuilder for Product instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    private java.lang.CharSequence primaryName;
    private java.lang.CharSequence secondaryName;
    private java.lang.CharSequence subline;
    private java.lang.CharSequence spec;
    private java.lang.CharSequence price;
    private java.lang.CharSequence url;

    /** Creates a new Builder */
    private Builder() {
      super(net.goldolphin.silvan.avro.Product.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(net.goldolphin.silvan.avro.Product.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Product instance */
    private Builder(net.goldolphin.silvan.avro.Product other) {
            super(net.goldolphin.silvan.avro.Product.SCHEMA$);
      if (isValidValue(fields()[0], other.primaryName)) {
        this.primaryName = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.primaryName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.secondaryName)) {
        this.secondaryName = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.secondaryName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subline)) {
        this.subline = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.subline);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.spec)) {
        this.spec = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.spec);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.url)) {
        this.url = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.url);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'primaryName' field */
    public java.lang.CharSequence getPrimaryName() {
      return primaryName;
    }
    
    /** Sets the value of the 'primaryName' field */
    public net.goldolphin.silvan.avro.Product.Builder setPrimaryName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.primaryName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'primaryName' field has been set */
    public boolean hasPrimaryName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'primaryName' field */
    public net.goldolphin.silvan.avro.Product.Builder clearPrimaryName() {
      primaryName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'secondaryName' field */
    public java.lang.CharSequence getSecondaryName() {
      return secondaryName;
    }
    
    /** Sets the value of the 'secondaryName' field */
    public net.goldolphin.silvan.avro.Product.Builder setSecondaryName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.secondaryName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'secondaryName' field has been set */
    public boolean hasSecondaryName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'secondaryName' field */
    public net.goldolphin.silvan.avro.Product.Builder clearSecondaryName() {
      secondaryName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'subline' field */
    public java.lang.CharSequence getSubline() {
      return subline;
    }
    
    /** Sets the value of the 'subline' field */
    public net.goldolphin.silvan.avro.Product.Builder setSubline(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.subline = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'subline' field has been set */
    public boolean hasSubline() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'subline' field */
    public net.goldolphin.silvan.avro.Product.Builder clearSubline() {
      subline = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'spec' field */
    public java.lang.CharSequence getSpec() {
      return spec;
    }
    
    /** Sets the value of the 'spec' field */
    public net.goldolphin.silvan.avro.Product.Builder setSpec(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.spec = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'spec' field has been set */
    public boolean hasSpec() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'spec' field */
    public net.goldolphin.silvan.avro.Product.Builder clearSpec() {
      spec = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.CharSequence getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public net.goldolphin.silvan.avro.Product.Builder setPrice(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.price = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'price' field */
    public net.goldolphin.silvan.avro.Product.Builder clearPrice() {
      price = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public net.goldolphin.silvan.avro.Product.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.url = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'url' field */
    public net.goldolphin.silvan.avro.Product.Builder clearUrl() {
      url = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public Product build() {
      try {
        Product record = new Product();
        record.primaryName = fieldSetFlags()[0] ? this.primaryName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.secondaryName = fieldSetFlags()[1] ? this.secondaryName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.subline = fieldSetFlags()[2] ? this.subline : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.spec = fieldSetFlags()[3] ? this.spec : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.price = fieldSetFlags()[4] ? this.price : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.url = fieldSetFlags()[5] ? this.url : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
