/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.goldolphin.silvan.avro;

@SuppressWarnings("all")
public interface SilvanApi {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SilvanApi\",\"namespace\":\"net.goldolphin.silvan.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"string\"}}}");
  java.lang.CharSequence send(net.goldolphin.silvan.avro.Message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SilvanApi {
    public static final org.apache.avro.Protocol PROTOCOL = net.goldolphin.silvan.avro.SilvanApi.PROTOCOL;
    void send(net.goldolphin.silvan.avro.Message message, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}